.MODEL SMALL
.STACK 100H
.DATA
MSG1 DB 'ENTER FIRST DIGIT:$'
MSG2 DB 13,10,'ENTER SECOND DIGIT:$'
EQUAL_MSG DB 13,10,'BOTH IS EQUAL:$'
GREATER_MSG DB 13,10,'FIRST IS GREATER:$'
LESSER_MSG DB 13,10,'SECOND IS GREATER:$'
.CODE
MAIN PROC
     MOV AX,@DATA
     MOV DS,AX
     
     MOV AH,09H
     LEA DX,MSG1
     INT 21H
     
     MOV AH,01H
     INT 21H
     SUB AL,'0'
     MOV BL,AL
     
     MOV AH,09H
     LEA DX,MSG2
     INT 21H
      
     MOV AH,01H
     INT 21H
     SUB AL,'0'
     MOV CL,AL 
     CMP BL,CL
     JE SHOW_EQUAL
     JA SHOW_GREATER
     
 SHOW_LESS:
  LEA DX,LESSER_MSG
  JMP DISPLAY
 SHOW_EQUAL:
  LEA DX,EQUAL_MSG
  JMP DISPLAY
 SHOW_GREATER:
  LEA DX,GREATER_MSG
 DISPLAY:
 MOV AH,09H
 INT 21H
 
 MOV AH,4CH
 INT 21H
 
 MAIN ENDP
END MAIN
     